apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: oauth2-proxy
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    name: ${INGRESS_GW}
    namespace: istio-system
  spec:
    workloadSelector:
      labels:
        app: ${INGRESS_GW}
    configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.jwt_authn
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              server_uri:
                uri: http://oauth2-proxy.${OAUTH_NS}.svc.cluster.local:4180
                cluster: outbound|4180||oauth2-proxy.${OAUTH_NS}.svc.cluster.local
                timeout: 10s
              authorizationRequest:
                allowedHeaders:
                  patterns:
                  - exact: cookie
              authorizationResponse:
                allowedUpstreamHeaders:
                  patterns:
                  - exact: authorization
parameters:
- description:  Specific ingress gateway that productpage service will be bound to be exposed
  name: INGRESS_GW
  required: true
- description:  Namespace where the OAuth2 proxy is deployed
  name: OAUTH_NS
  required: true