kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: details
spec:
  hosts:
    - details
  http:
    - route:
        - destination:
            host: details
            subset: v1
          weight: 100
--- 
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: details
spec:
  host: details
  subsets:
    - labels:
        version: v1
      name: v1
