kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: ratings
spec:
  hosts:
    - ratings
  http:
    - route:
        - destination:
            host: ratings
            subset: v1
          weight: 100
--- 
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: ratings
spec:
  host: ratings
  subsets:
    - labels:
        version: v1
      name: v1
