kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v3
          weight: 100
--- 
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
    - labels:
        version: v3
      name: v3
