---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubi
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: ubi
    spec:
      containers:
      - name: ubi
        image: registry.redhat.io/ubi8/ubi:latest
        command: ["sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
